#!perl
use v5.12;
use utf8;
use strict;
use warnings;

use Test::More tests => 1;

use Video::Subtitle::OO::ASS::File;
use Video::Subtitle::OO::SRT::File;

my $out = <<'END';
[Script Info]
; Script generated by Aegisub r6190+50 (branch master)
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
PlayResX: 640
PlayResY: 360
Collisions: Normal

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.56,0:00:03.56,Default,,0,0,0,,あッ
Dialogue: 0,0:00:03.56,0:00:06.23,Default,,0,0,0,,来たの？　遅かったじゃない
Dialogue: 0,0:00:06.23,0:00:08.73,Default,,0,0,0,,えっと　柏崎
Dialogue: 0,0:00:08.73,0:00:10.90,Default,,0,0,0,,星奈って呼びなさい\Nえッ？
END

my $srt = <<'END';
1
00:00:01,560 --> 00:00:03,560
あッ

2
00:00:03,560 --> 00:00:06,230
来たの？　遅かったじゃない

3
00:00:06,230 --> 00:00:08,730
えっと　柏崎

4
00:00:08,730 --> 00:00:10,900
星奈って呼びなさい
えッ？
END

is(
    Video::Subtitle::OO::SRT::File->create_from_subtitle(
        Video::Subtitle::OO::ASS::File->create_from_string($out)
      )->to_string,
    $srt,
    'Unicode string worked'
);
